-- SONAVERA Orders schema
create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  order_id text unique not null,
  razorpay_order_id text unique,
  payment_id text,
  payment_status text not null default 'created',
  customer_name text,
  customer_mobile text,
  customer_email text,
  delivery_address text,
  items jsonb not null default '[]'::jsonb,
  amount numeric(12,2) not null default 0,
  currency text not null default 'INR',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.orders enable row level security;

-- Customer browsers must not be able to read/write the orders table directly.
-- The Next.js server uses SUPABASE_SECRET_KEY for trusted writes/reads.
drop policy if exists "orders_no_public_read" on public.orders;
drop policy if exists "orders_no_public_insert" on public.orders;
drop policy if exists "orders_no_public_update" on public.orders;

create policy "orders_no_public_read"
on public.orders for select to anon, authenticated using (false);

create policy "orders_no_public_insert"
on public.orders for insert to anon, authenticated with check (false);

create policy "orders_no_public_update"
on public.orders for update to anon, authenticated using (false) with check (false);

create index if not exists orders_created_at_idx on public.orders (created_at desc);
create index if not exists orders_payment_status_idx on public.orders (payment_status);
